### ISSUE TITLE
Block not found

### ISSUE THREAD

**Issue by scream4ik** [NethermindEth/nethermind#2284]
```
>>> web3.eth.getBlock(8659695)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/app/.local/lib/python3.7/site-packages/web3/eth.py", line 222, in getBlock
    raise BlockNotFound(f"Block with id: {block_identifier} not found.")
web3.exceptions.BlockNotFound: Block with id: 8659695 not found.
```
but https://etherscan.io/block/8659695

With the latest blocks all fine. How it could be?

Docker image: nethermind/nethermind:1.8.95

**Comment by tkstanczak** [comment]
@scream4ik have you done a default config sync?
this would not download the bodies of the blocks from before the fast sync transition (saves space and sync time)

you would need to use --Sync.DownloadBodiesInFastSync during sync

**Comment by scream4ik** [comment]
I added `--Sync.DownloadBodiesInFastSync` and re-sync node from scratch. But the same behavior. 

My docker-compose:
```
version: '3.8'
services:
  nethermind:
    image: nethermind/nethermind:1.8.98
    environment:
      - NETHERMIND_JSONRPCCONFIG_HOST=0.0.0.0
      - NETHERMIND_JSONRPCCONFIG_ENABLED=true
      - NETHERMIND_CONFIG=mainnet
      - NETHERMIND_JSONRPCCONFIG_PORT=8000
      - NETHERMIND_SYNCCONFIG_DOWNLOADBODIESINFASTSYNC=true
    ports:
      - "8000:8000"
    volumes:
    - ./docker_data/nethermind_db:/nethermind/nethermind_db
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 14G
      restart_policy:
        condition: on-failure
```
