### ISSUE TITLE
error handling sendRawTransaction from jsonrpc with 1Gwei

### ISSUE THREAD

**Issue by superflo22** [NethermindEth/nethermind#3651]
**Describe the bug**
This happends when sending transactions on xdai chain.
_**Found out that txs with more than 1Gwei are fine**_ 

**To Reproduce**
1. Have a xdai node (mine is not a validator) 
2. Connect metamask 
3. Make tx with **1 Gwei**

**Expected behavior**
Transaction confirmed

**LOGS**
Docker log output
`Error when handling ID 2145, eth_sendRawTransaction(someData) | {"jsonrpc":"2.0","error":{"code":-32010,"message":"Filtered"},"id":2145}`

**Additional context**
Node is in docker and configured via:
```
version: '3.8'
services:
  nethermind:
    image: nethermind/nethermind
    restart: always
    command: '--config xdai --datadir data --JsonRpc.Enabled true --Metrics.Enabled true'
    volumes:
      - './data:/nethermind/data'
    network_mode: host
```
