### ISSUE TITLE
Ethstats module does not show node's location

### ISSUE THREAD

**Issue by plato-gno** [NethermindEth/nethermind#5083]
**Describe the bug**

- Location of node does not show up in Ethstats
- Is there a flag we need to turn on to show the node's location?
- Rationale: Gnosis is doing research into the "1-node-per-country" initiative and needs an easy way for BD side to track node locations

What was expected: 
- Nethermind's node shows its location
![image](https://user-images.githubusercontent.com/98335261/210393849-e884291d-15a8-452e-8803-649c9e6cf335.png)

- However mine (with ethstats module) does not
![image](https://user-images.githubusercontent.com/98335261/210345241-f3151761-2347-4bf4-8c1b-6e15b0c97ee5.png)

**To Reproduce**

```
version: "3"
services:

  execution:
    container_name: execution
    image: nethermind/nethermind:latest
    restart: unless-stopped
    stop_grace_period: 1m
    networks:
      - gnosis_net
    ports:
      - 30304:30304/tcp # p2p
      - 30304:30304/udp # p2p
    expose:
      - 8545 # rpc
      - 8551 # engine api
      - 30303 # p2p port
    volumes:
      - /home/$USER/gnosis/execution:/data
      - /home/$USER/gnosis/jwtsecret/jwt.hex:/jwt.hex
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - --config=xdai
      - --datadir=/data
      - --log=INFO
      # Network
      - --Network.DiscoveryPort=30303
      - --Network.P2PPort=30303
      - --HealthChecks.Enabled=true
      - --Pruning.CacheMb=2048
      # Merge
      - --Merge.Enabled=true
      # EthStats
      - --EthStats.Enabled=true
      - --EthStats.Server=wss://ethstats.gnosischain.com/api
      - --EthStats.Name=eigenvector-gnosis-2
      - --EthStats.Secret=...
      - --EthStats.Contact=...
      # Sync mode
      - --Sync.FastSync=true
      - --Sync.SnapSync=false
      # JsonRPC
      - --JsonRpc.Enabled=true
      - --JsonRpc.Host=0.0.0.0
      - --JsonRpc.Port=8545
      - --JsonRpc.EnabledModules=[Web3,Eth,Subscribe,Net,]
      - --JsonRpc.JwtSecretFile=/jwt.hex
      - --JsonRpc.EngineHost=0.0.0.0
      - --JsonRpc.EnginePort=8551
    logging:
      driver: "local"
```
