### ISSUE TITLE
[Pectra] EIP-7702 transaction RLP decoding issue

### ISSUE THREAD

**Issue by lattejed** [NethermindEth/nethermind#7236]
Hello!

We're currently testing your pectra branch in a private devnet

We're encountering an RLP decoding issue related to the `authorization_list` that has been added to EIP-7702 transactions

I _believe_ (looking at https://github.com/NethermindEth/nethermind/pull/7232) you're using a version of the `authorization_list` from an earlier draft of the EIP

Current version here: https://eips.ethereum.org/EIPS/eip-7702

The current version of the `authorization_list` is:

```
authorization_list = [[chain_id, address, [nonce], y_parity, r, s], ...]
```

The `nonce` parameter is optional where an empty list is used for 'not required'

We're using the version represented by this (kurtosis):

```
participants:
  - el_type: nethermind
    el_image: nethermindeth/nethermind:pectra
...
```
